const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.LocalStorage,
		C3.Plugins.Touch,
		C3.Plugins.Mouse,
		C3.Plugins.Browser,
		C3.Plugins.Audio,
		C3.Plugins.PlatformInfo,
		C3.Plugins.Sprite,
		C3.Behaviors.scrollto,
		C3.Behaviors.Sin,
		C3.Behaviors.Tween,
		C3.Plugins.TiledBg,
		C3.Behaviors.Fade,
		C3.Behaviors.LOS,
		C3.Behaviors.Physics,
		C3.Plugins.NinePatch,
		C3.Behaviors.shadowcaster,
		C3.Behaviors.solid,
		C3.Plugins.Spritefont2,
		C3.Plugins.Arr,
		C3.Behaviors.Rotate,
		C3.Plugins.Particles,
		C3.Plugins.shadowlight,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.Sprite.Acts.SetY,
		C3.Plugins.System.Exps.viewportbottom,
		C3.Plugins.Sprite.Exps.Height,
		C3.Plugins.System.Acts.Wait,
		C3.Behaviors.Fade.Acts.RestartFade,
		C3.Behaviors.Fade.Cnds.OnFadeInEnd,
		C3.Behaviors.Sin.Acts.SetEnabled,
		C3.Plugins.Touch.Cnds.OnTouchEnd,
		C3.Plugins.Sprite.Cnds.IsOnScreen,
		C3.Plugins.Sprite.Cnds.IsBoolInstanceVarSet,
		C3.Plugins.Sprite.Acts.SetBoolInstanceVar,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.System.Acts.SetGroupActive,
		C3.Behaviors.Tween.Acts.TweenOneProperty,
		C3.Behaviors.Tween.Cnds.OnTweensPingPong,
		C3.Plugins.NinePatch.Exps.Y,
		C3.Plugins.Touch.Cnds.OnTouchStart,
		C3.Plugins.Touch.Cnds.IsTouchingObject,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.System.Cnds.Compare,
		C3.Plugins.System.Exps.timescale,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.System.Acts.SetLayerOpacity,
		C3.Plugins.Audio.Cnds.IsTagPlaying,
		C3.Plugins.System.Cnds.For,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.Arr.Exps.At,
		C3.Plugins.System.Exps.loopindex,
		C3.Plugins.Arr.Cnds.CompareXY,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.Sprite.Acts.SetX,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.System.Cnds.ForEach,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Plugins.Spritefont2.Acts.SetText,
		C3.Plugins.Spritefont2.Acts.SetPos,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.System.Cnds.IsMobile,
		C3.Plugins.Sprite.Cnds.CompareFrame,
		C3.Plugins.Mouse.Cnds.IsOverObject,
		C3.Plugins.Sprite.Acts.SubInstanceVar,
		C3.Plugins.Sprite.Acts.AddInstanceVar,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.System.Exps.replace,
		C3.Plugins.System.Exps.layoutname,
		C3.Behaviors.Physics.Acts.SetWorldGravity,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.TiledBg.Acts.MoveToBottom,
		C3.Plugins.TiledBg.Acts.SetOpacity,
		C3.Plugins.TiledBg.Acts.SetPosToObject,
		C3.Plugins.TiledBg.Acts.Destroy,
		C3.Plugins.Sprite.Cnds.IsOnLayer,
		C3.Plugins.System.Exps.originalviewportheight,
		C3.Plugins.Audio.Acts.Stop,
		C3.Plugins.Sprite.Acts.MoveToLayer,
		C3.Plugins.System.Cnds.IsBetweenAngles,
		C3.Plugins.Arr.Acts.SetXY,
		C3.Plugins.System.Exps.random,
		C3.Plugins.Particles.Acts.SetSpraying,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Behaviors.scrollto.Acts.Shake,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Plugins.Sprite.Acts.MoveToBottom,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.NinePatch.Exps.X,
		C3.Plugins.NinePatch.Acts.SetSize,
		C3.Plugins.NinePatch.Exps.Width,
		C3.Plugins.NinePatch.Exps.Height,
		C3.Plugins.NinePatch.Acts.SetAngle,
		C3.Plugins.NinePatch.Exps.Angle,
		C3.Plugins.NinePatch.Acts.SetOpacity,
		C3.Plugins.Sprite.Acts.SetSize,
		C3.Plugins.Sprite.Exps.Width,
		C3.Plugins.Sprite.Acts.SetAngle,
		C3.Plugins.Sprite.Exps.Angle,
		C3.Plugins.Sprite.Acts.SetOpacity,
		C3.Plugins.Touch.Cnds.IsInTouch,
		C3.Plugins.TiledBg.Cnds.IsOnScreen,
		C3.Plugins.TiledBg.Acts.SetTowardPosition,
		C3.Plugins.Touch.Exps.X,
		C3.Plugins.Touch.Exps.Y,
		C3.Behaviors.LOS.Acts.CastRay,
		C3.Plugins.TiledBg.Exps.Angle,
		C3.Behaviors.LOS.Cnds.RayIntersected,
		C3.Plugins.TiledBg.Acts.SetWidth,
		C3.Plugins.TiledBg.Exps.X,
		C3.Plugins.TiledBg.Exps.Y,
		C3.Behaviors.LOS.Exps.HitX,
		C3.Behaviors.LOS.Exps.HitY,
		C3.Behaviors.Physics.Acts.SetVelocity,
		C3.Plugins.Sprite.Cnds.OnDestroyed,
		C3.Plugins.Sprite.Exps.LayerName,
		C3.Plugins.Sprite.Cnds.CompareX,
		C3.Plugins.System.Exps.originalviewportwidth,
		C3.Plugins.Sprite.Exps.Count,
		C3.Behaviors.Tween.Cnds.IsPlaying,
		C3.Plugins.Sprite.Cnds.CompareWidth,
		C3.Plugins.Sprite.Cnds.CompareHeight,
		C3.Behaviors.Tween.Acts.TweenTwoProperties,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.Audio.Acts.SetSilent,
		C3.Plugins.Audio.Cnds.IsSilent,
		C3.Plugins.Sprite.Cnds.IsAnimPlaying,
		C3.Plugins.Browser.Acts.GoToURLWindow,
		C3.Plugins.LocalStorage.Cnds.OnItemExists,
		C3.Plugins.LocalStorage.Acts.GetItem,
		C3.Plugins.LocalStorage.Cnds.OnItemMissing,
		C3.Plugins.LocalStorage.Acts.SetItem,
		C3.Plugins.Arr.Exps.AsJSON,
		C3.Plugins.LocalStorage.Cnds.OnItemGet,
		C3.Plugins.Arr.Acts.JSONLoad,
		C3.Plugins.LocalStorage.Exps.ItemValue,
		C3.Plugins.LocalStorage.Acts.CheckItemExists,
		C3.Plugins.System.Exps.layeropacity,
		C3.Plugins.System.Cnds.LayerCmpOpacity,
		C3.Plugins.System.Acts.SetTimescale,
		C3.Plugins.System.Acts.GoToLayoutByName,
		C3.Plugins.Sprite.Cnds.OnCreated,
		C3.Behaviors.Rotate.Acts.SetSpeed,
		C3.Plugins.System.Exps.choose,
		C3.Plugins.Sprite.Exps.AnimationFrameCount,
		C3.Plugins.Sprite.Acts.MoveToTop,
		C3.Plugins.Particles.Acts.SetY,
		C3.Plugins.System.Exps.viewporttop,
		C3.Plugins.Particles.Exps.LayerName,
		C3.Plugins.Particles.Acts.SetXRandomiser,
		C3.Plugins.System.Exps.viewportwidth
	];
};
self.C3_JsPropNameTable = [
	{LocalStorage: 0},
	{Touch: 0},
	{Mouse: 0},
	{Browser: 0},
	{Audio: 0},
	{PlatformInfo: 0},
	{Game_Tittle: 0},
	{show: 0},
	{ScrollTo: 0},
	{menuManager: 0},
	{Sine: 0},
	{Tween: 0},
	{hand: 0},
	{line_tuto: 0},
	{tutorial: 0},
	{line_ui: 0},
	{paused: 0},
	{win: 0},
	{defeat: 0},
	{countDown: 0},
	{uiBlock: 0},
	{gameManager: 0},
	{goGame: 0},
	{Fade: 0},
	{taptoplay: 0},
	{fire: 0},
	{LineOfSight: 0},
	{Physics: 0},
	{ball: 0},
	{ShadowCaster: 0},
	{block: 0},
	{Solid: 0},
	{blockCorner: 0},
	{Sine2: 0},
	{star: 0},
	{big: 0},
	{mWidth: 0},
	{mHeight: 0},
	{active: 0},
	{Nivel: 0},
	{btnNivel: 0},
	{nHoja: 0},
	{selectorManager: 0},
	{bgSelector: 0},
	{txtBtnNivel: 0},
	{txtUI: 0},
	{Variables: 0},
	{btnCredits: 0},
	{btnMoreGames: 0},
	{btnPlay: 0},
	{btnBack: 0},
	{btnArrowLeft: 0},
	{btnArrowRight: 0},
	{btnMenu: 0},
	{btnContinuar: 0},
	{btnReset: 0},
	{btnSound: 0},
	{QkyGamesLogo: 0},
	{bgCredits: 0},
	{circleExplosion: 0},
	{fadeSubMenu: 0},
	{Rotate: 0},
	{confetti: 0},
	{confettiWin: 0},
	{confetiTop: 0},
	{starsSystemParticle: 0},
	{ballParticle: 0},
	{blockWhiteFX: 0},
	{blockCornerFX: 0},
	{starParticle: 0},
	{ballWin: 0},
	{blockWin: 0},
	{winTitle: 0},
	{ShadowLight: 0},
	{Buttons: 0},
	{SineElements: 0},
	{Blocks: 0},
	{totStars: 0},
	{Level: 0},
	{BALLSPEED: 0},
	{mag: 0},
	{tiempo: 0},
	{GAMENAME_SAVE: 0},
	{TOTLEVELS: 0},
	{layerIn: 0},
	{layerOut: 0},
	{FADESPEED: 0},
	{Layout: 0},
	{newlayer: 0}
];

self.InstanceType = {
	LocalStorage: class extends self.IInstance {},
	Touch: class extends self.IInstance {},
	Mouse: class extends self.IInstance {},
	Browser: class extends self.IInstance {},
	Audio: class extends self.IInstance {},
	PlatformInfo: class extends self.IInstance {},
	Game_Tittle: class extends self.ISpriteInstance {},
	menuManager: class extends self.ISpriteInstance {},
	hand: class extends self.ISpriteInstance {},
	line_tuto: class extends self.ITiledBackgroundInstance {},
	tutorial: class extends self.ISpriteInstance {},
	line_ui: class extends self.ITiledBackgroundInstance {},
	gameManager: class extends self.ISpriteInstance {},
	taptoplay: class extends self.ISpriteInstance {},
	ball: class extends self.ISpriteInstance {},
	block: class extends self.IWorldInstance {},
	blockCorner: class extends self.ISpriteInstance {},
	star: class extends self.ISpriteInstance {},
	btnNivel: class extends self.ISpriteInstance {},
	nHoja: class extends self.ISpriteInstance {},
	selectorManager: class extends self.ISpriteInstance {},
	bgSelector: class extends self.ISpriteInstance {},
	txtBtnNivel: class extends self.ISpriteFontInstance {},
	txtUI: class extends self.ISpriteFontInstance {},
	Variables: class extends self.IArrayInstance {},
	btnCredits: class extends self.ISpriteInstance {},
	btnMoreGames: class extends self.ISpriteInstance {},
	btnPlay: class extends self.ISpriteInstance {},
	btnBack: class extends self.ISpriteInstance {},
	btnArrowLeft: class extends self.ISpriteInstance {},
	btnArrowRight: class extends self.ISpriteInstance {},
	btnMenu: class extends self.ISpriteInstance {},
	btnContinuar: class extends self.ISpriteInstance {},
	btnReset: class extends self.ISpriteInstance {},
	btnSound: class extends self.ISpriteInstance {},
	QkyGamesLogo: class extends self.ISpriteInstance {},
	bgCredits: class extends self.ISpriteInstance {},
	circleExplosion: class extends self.ISpriteInstance {},
	fadeSubMenu: class extends self.ISpriteInstance {},
	confetti: class extends self.ISpriteInstance {},
	confettiWin: class extends self.IParticlesInstance {},
	confetiTop: class extends self.IParticlesInstance {},
	starsSystemParticle: class extends self.IParticlesInstance {},
	ballParticle: class extends self.ISpriteInstance {},
	blockWhiteFX: class extends self.IWorldInstance {},
	blockCornerFX: class extends self.ISpriteInstance {},
	starParticle: class extends self.ISpriteInstance {},
	ballWin: class extends self.ISpriteInstance {},
	blockWin: class extends self.IWorldInstance {},
	winTitle: class extends self.ISpriteInstance {},
	ShadowLight: class extends self.IShadowLightInstance {},
	Buttons: class extends self.ISpriteInstance {},
	SineElements: class extends self.ISpriteInstance {},
	Blocks: class extends self.IWorldInstance {}
}